# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import homeinventory.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(homeinventory.inventory.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
