# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171017_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='estimated_current_value',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='id_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='purchased_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchased_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_type',
            field=models.CharField(choices=[('001', 'original manufacturer warranty'), ('002', 'insurance warranty underwritten and regulated as insurance'), ('003', 'lifetime warranty'), ('004', 'satisfaction guarantee'), ('005', 'implied warranty'), ('006', 'other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
