# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeinventory.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_itemattachment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=homeinventory.inventory.models.user_directory_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(homeinventory.inventory.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
