# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_itemphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('who', models.CharField(max_length=255)),
                ('when', models.DateTimeField()),
                ('why', models.CharField(blank=True, max_length=500, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
    ]
